name = "intily-ai-news"
main = "src/main.py"
compatibility_date = "2026-09-05"
compatibility_flags = ["python_workers"]

[observability]
enabled = true

[triggers]
crons = ["* * * * *"]

[[kv_namespaces]]
binding = "STATE"
id = "8d608fcdfed54432b9c84c9c13a1777d"

[ai]
binding = "AI"

[browser]
binding = "BROWSER"
